# Generated by Django 4.2.7 on 2023-12-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_picture', models.ImageField(blank=True, null=True, upload_to='cat_pics')),
                ('breed', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('traits', models.TextField()),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cat',
                'verbose_name_plural': 'Cats',
            },
        ),
    ]
