# Generated by Django 4.2.7 on 2023-12-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/cat_images'),
        ),
    ]
