# Generated by Django 4.2.7 on 2023-12-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSite', '0002_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/cat_pics'),
        ),
    ]
