# Generated by Django 4.2.7 on 2023-12-13 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSite', '0003_alter_cat_cat_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='image',
        ),
    ]
