# Generated by Django 5.0 on 2023-12-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0003_article_comment_article_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='UserAuth.comment'),
        ),
    ]
