# Generated by Django 5.0 on 2023-12-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0005_alter_article_thumbnails_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='num_comments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
